"use client";

import React from "react";
import { Sparkles, Database, Layers, ArrowRight, Code, Cpu, Globe, Zap, Server, Shield, Activity, FileText } from "lucide-react";
import GlassCard from "@/components/ui/GlassCard";

interface GenesisArchitectProps {
    genesisIdea: string;
    setGenesisIdea: (value: string) => void;
    handleGenesisStart: () => void;
    isArchitecting: boolean;
    genesisPlan: any;
    onClose?: () => void;
    onReset?: () => void;
}

export default function GenesisArchitect({
    genesisIdea,
    setGenesisIdea,
    handleGenesisStart,
    isArchitecting,
    genesisPlan,
    onClose,
    onReset
}: GenesisArchitectProps) {

    // 🖨️ PDF GENERATOR (The "Smart Print" Engine)
    const handleDownloadPDF = () => {
        if (!genesisPlan) return;

        const printWindow = window.open('', '_blank');
        if (!printWindow) {
            alert("Please allow popups to download the blueprint.");
            return;
        }

        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>${genesisPlan.appName} - Genesis Blueprint</title>
                <style>
                    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px; }
                    h1 { font-size: 36px; color: #000; margin-bottom: 5px; letter-spacing: -1px; }
                    .tagline { font-size: 18px; color: #666; font-style: italic; margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
                    h2 { font-size: 20px; color: #000; text-transform: uppercase; border-bottom: 2px solid #000; padding-bottom: 5px; margin-top: 40px; margin-bottom: 15px; letter-spacing: 1px; }
                    h3 { font-size: 16px; color: #444; font-weight: bold; margin-top: 25px; margin-bottom: 10px; }
                    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
                    .stack-item { background: #f5f5f5; padding: 10px 15px; border-radius: 6px; font-weight: bold; font-size: 14px; border: 1px solid #ddd; }
                    ul { padding-left: 20px; }
                    li { margin-bottom: 8px; }
                    .code-block { background: #f0f0f0; padding: 15px; border-radius: 8px; font-family: 'Courier New', monospace; font-size: 13px; white-space: pre-wrap; border: 1px solid #ccc; }
                    .roadmap-step { margin-bottom: 15px; padding-left: 15px; border-left: 3px solid #000; }
                    .roadmap-phase { font-weight: bold; font-size: 12px; color: #666; text-transform: uppercase; }
                    .footer { margin-top: 60px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
                </style>
            </head>
            <body>
                <h1>${genesisPlan.appName}</h1>
                <div class="tagline">"${genesisPlan.tagline}"</div>

                <h2>Technical Stack</h2>
                <div class="grid">
                    ${genesisPlan.techStack.map((tech: string) => `<div class="stack-item">${tech}</div>`).join('')}
                </div>

                <h2>Core Features (MVP)</h2>
                <ul>
                    ${genesisPlan.coreFeatures?.map((feature: string) => `<li>${feature}</li>`).join('')}
                </ul>

                <h2>Data Architecture</h2>
                <div class="code-block">${genesisPlan.databaseStructure}</div>

                <h2>Execution Roadmap</h2>
                <div>
                    ${genesisPlan.stepByStepPlan.map((step: string, i: number) => `
                        <div class="roadmap-step">
                            <div class="roadmap-phase">Phase ${i + 1}</div>
                            <div>${step}</div>
                        </div>
                    `).join('')}
                </div>

                <div class="footer">
                    Generated by HUSKYMIND GENESIS ARCHITECT • ${new Date().toLocaleDateString()}
                </div>

                <script>
                    window.onload = function() { window.print(); window.close(); }
                </script>
            </body>
            </html>
        `;

        printWindow.document.write(htmlContent);
        printWindow.document.close();
    };

    return (
        <div className="h-full w-full overflow-y-auto bg-black p-6 md:p-12 animate-in fade-in slide-in-from-bottom-6 custom-scrollbar pb-24">

            {/* ===================================================================================== */}
            {/* 🧬 GENESIS ARCHITECT UI (The Project Builder) */}
            {/* ===================================================================================== */}
            <div className="max-w-5xl mx-auto">

                {/* HEADER */}
                <div className="text-center mb-12 relative">
                    {onClose && (
                        <button onClick={onClose} className="absolute left-0 top-0 text-gray-500 hover:text-white transition-colors">
                            ← BACK
                        </button>
                    )}
                    <h1 className="text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-600 mb-4 tracking-tight">
                        GENESIS ARCHITECT
                    </h1>
                    <p className="text-gray-400 text-lg">
                        Stop watching tutorials. Start building startups.
                        <span className="block text-sm text-cyan-500 mt-2">AI-POWERED CTO & ARCHITECT</span>
                    </p>
                </div>

                {/* 1. INPUT SECTION (The Spark) */}
                {!genesisPlan && (
                    <div className="relative animate-in fade-in zoom-in-95 duration-500">
                        <div className="bg-black border border-cyan-900/50 rounded-3xl p-8 relative overflow-hidden shadow-2xl shadow-cyan-900/20 mb-8 backdrop-blur-sm z-10">
                            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-cyan-500 via-purple-500 to-cyan-500"></div>

                            <label className="block text-cyan-400 text-xs font-bold tracking-widest uppercase mb-3 drop-shadow-[0_0_5px_rgba(34,211,238,0.5)]">
                                Project Brief //
                            </label>

                            <div className="flex flex-col md:flex-row gap-4">
                                <input
                                    type="text"
                                    placeholder="e.g. A Tinder for adopting stray dogs..."
                                    className="flex-1 bg-gray-900/50 border border-gray-800 rounded-xl p-6 text-white text-lg focus:border-cyan-500 outline-none transition-all placeholder:text-gray-700 font-mono focus:shadow-[0_0_20px_rgba(6,182,212,0.15)] ring-offset-2 ring-offset-black"
                                    value={genesisIdea || ""}
                                    onChange={(e) => setGenesisIdea(e.target.value)}
                                    onKeyDown={(e) => e.key === 'Enter' && handleGenesisStart()}
                                />
                                <button
                                    onClick={handleGenesisStart}
                                    disabled={isArchitecting || !genesisIdea}
                                    className="px-10 py-4 bg-cyan-600 hover:bg-cyan-500 text-white font-black rounded-xl text-xl tracking-wide transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-cyan-500/40 whitespace-nowrap active:scale-95"
                                >
                                    {isArchitecting ? "ARCHITECTING..." : "GENERATE BLUEPRINT"}
                                </button>
                            </div>
                        </div>

                        {/* STARTER IDEAS (Filling the Void) */}
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 opacity-50 hover:opacity-100 transition-opacity duration-500 mb-12">
                            {[
                                "A decentralized platform for freelance journalists",
                                "AI-powered personalized nutrition coach app",
                                "Augmented Reality interior design tool"
                            ].map((idea, i) => (
                                <button
                                    key={i}
                                    onClick={() => setGenesisIdea(idea)}
                                    className="p-4 rounded-xl border border-gray-800 bg-gray-900/30 hover:bg-gray-800 hover:border-cyan-500/50 text-left transition-all group"
                                >
                                    <div className="text-cyan-500/50 text-[10px] font-mono mb-2 group-hover:text-cyan-400">TEMPLATE 0{i + 1}</div>
                                    <div className="text-gray-400 text-sm group-hover:text-white line-clamp-2">"{idea}"</div>
                                </button>
                            ))}
                        </div>

                        {/* DECORATIVE BACKGROUND ELEMENTS (The "Stunning" Part) */}
                        <div className="absolute top-[80%] left-1/2 -translate-x-1/2 w-full max-w-4xl h-96 pointer-events-none -z-10 opacity-30">
                            {/* Central Beam */}
                            <div className="absolute left-1/2 -translate-x-1/2 top-0 w-[1px] h-full bg-gradient-to-b from-cyan-500/0 via-cyan-500 to-cyan-500/0"></div>

                            {/* Floor Grid */}
                            <div className="absolute bottom-0 w-full h-full bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-cyan-900/20 via-black to-black mask-image-gradient-b"></div>
                            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] border border-cyan-500/20 rounded-[100%] rotate-x-[60deg] animate-[spin_20s_linear_infinite]"></div>
                            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[200px] border border-purple-500/20 rounded-[100%] rotate-x-[60deg] animate-[spin_15s_linear_infinite_reverse]"></div>

                            <div className="absolute bottom-10 left-1/2 -translate-x-1/2 text-cyan-900/40 text-[10px] tracking-[1em] font-black uppercase text-center">
                                Awaiting System Input<br />
                                <span className="text-[20px] animate-pulse">●</span>
                            </div>
                        </div>
                    </div>
                )}

                {/* 2. THE BLUEPRINT RESULT (The Magic) */}
                {genesisPlan && (
                    <div className="mt-12 space-y-8 animate-in zoom-in-95 duration-700">

                        {/* ACTION BUTTONS (Reset & Download) */}
                        <div className="flex justify-center gap-4 mb-8">
                            <button
                                onClick={onReset}
                                className="px-8 py-3 bg-gray-900 hover:bg-gray-800 border border-gray-700 hover:border-gray-500 text-white rounded-full font-bold tracking-wide transition-all shadow-lg flex items-center gap-2 group"
                            >
                                <Sparkles size={16} className="text-cyan-500 group-hover:rotate-12 transition-transform" />
                                START NEW SESSION
                            </button>
                            <button
                                onClick={handleDownloadPDF}
                                className="px-8 py-3 bg-cyan-900/30 hover:bg-cyan-900/50 border border-cyan-700/50 hover:border-cyan-500 text-cyan-400 hover:text-cyan-200 rounded-full font-bold tracking-wide transition-all shadow-lg flex items-center gap-2 group"
                            >
                                <FileText size={16} className="text-cyan-400 group-hover:scale-110 transition-transform" />
                                DOWNLOAD BLUEPRINT
                            </button>
                        </div>

                        {/* A. TITLE CARD */}
                        <div className="text-center">
                            <div className="inline-block px-4 py-1 rounded-full border border-cyan-500/30 bg-cyan-950/30 text-cyan-400 text-xs font-mono mb-4">
                                PROJECT CODENAME
                            </div>
                            <h2 className="text-6xl font-black text-white mb-2">{genesisPlan.appName}</h2>
                            <p className="text-2xl text-gray-400 italic font-light">"{genesisPlan.tagline}"</p>
                        </div>

                        {/* B. TECH STACK GRID */}
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            {genesisPlan.techStack.map((tech: string, i: number) => (
                                <div key={i} className="p-4 bg-gray-900 border border-gray-800 rounded-xl text-center group hover:border-purple-500 transition-all">
                                    <div className="text-purple-500 text-xs font-bold uppercase mb-2">LAYER {i + 1}</div>
                                    <div className="text-white font-bold text-lg group-hover:scale-110 transition-transform">{tech}</div>
                                </div>
                            ))}
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                            {/* C. FEATURES LIST */}
                            <div className="p-8 bg-gray-900/30 border border-gray-800 rounded-3xl">
                                <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                                    <span className="text-green-500">⚡</span> MVP FEATURES
                                </h3>
                                <ul className="space-y-4">
                                    {genesisPlan.coreFeatures?.map((feature: string, i: number) => (
                                        <li key={i} className="flex gap-3 text-gray-300">
                                            <span className="text-green-500 font-mono">0{i + 1}.</span>
                                            <span>{feature}</span>
                                        </li>
                                    ))}
                                </ul>
                            </div>

                            {/* D. DATABASE SCHEMA */}
                            <div className="p-8 bg-gray-900/30 border border-gray-800 rounded-3xl">
                                <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                                    <span className="text-blue-500">🗄️</span> DATA ARCHITECTURE
                                </h3>
                                <div className="font-mono text-sm text-blue-300/80 bg-black/50 p-6 rounded-xl border border-blue-900/30 leading-relaxed whitespace-pre-wrap">
                                    {genesisPlan.databaseStructure}
                                </div>
                            </div>
                        </div>

                        {/* E. ROADMAP TIMELINE */}
                        <div className="p-8 bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-3xl">
                            <h3 className="text-xl font-bold text-white mb-8 flex items-center gap-2">
                                <span className="text-yellow-500">📅</span> EXECUTION ROADMAP
                            </h3>
                            <div className="space-y-6 relative border-l-2 border-gray-800 ml-3 pl-8">
                                {genesisPlan.stepByStepPlan.map((step: string, i: number) => (
                                    <div key={i} className="relative">
                                        <div className="absolute -left-[41px] top-1 w-5 h-5 rounded-full bg-gray-900 border-2 border-yellow-600"></div>
                                        <div className="text-yellow-500 text-xs font-bold uppercase mb-1">PHASE {i + 1}</div>
                                        <p className="text-gray-300 text-lg">{step}</p>
                                    </div>
                                ))}
                            </div>
                        </div>

                    </div>
                )}
            </div>
        </div>
    );
}
